spring.application.name=DSFW_team_proj
spring.datasource.url=jdbc:mariadb://localhost:3306/dsfw_team_proj
spring.datasource.username=root
spring.datasource.password= root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true